# Generated by Django 5.0 on 2024-02-10 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_subscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
